version: 2

sources:

  - name: tmp_dim_product_snapshot
    project: noble-district-469815-s9
    dataset: curated
    tables:
      - name: tmp_dim_product_snapshot
        identifier: tmp_dim_product_snapshot
